xsetwacom --set 'HUION Huion Tablet Pad pad' Button 1 "key +ctrl +z"
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 2 "key +ctrl +y"
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 3 "key +ctrl +s"
#xsetwacom --set 'HUION Huion Tablet Pen stylus' Button 2 "key +pgdn"
#xsetwacom --set 'HUION Huion Tablet Pen stylus' Button 3 "key +pgup"
